#!/bin/bash

# Description  : Safely create a UTF-8 MySQL db.
# Usage        : db mysql-create <db-name>
# Dependencies : mysql-client
# Example      : db mysql-create my_db
# Notes        :
# Source       :

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <db_name>"
  exit 1
fi

/usr/bin/mysqld_safe > /dev/null 2>&1 &

echo "=> Creating database $1"
RET=1
while [[ RET -ne 0 ]]; do
  sleep 5
  mysql -uroot -e "CREATE DATABASE $1 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
  RET=$?
done

mysqladmin -uroot shutdown

echo "=> Done!"