#!/usr/bin/php
<?php

/**
 * Description  : Sync MongoDB from remote to local host.
 * Usage        : db sync-mongo [get|put] [path/to/config.ini]
 * Dependencies : php, mongodb
 * Example      : db sync-mogno get config.ini
 * Notes        : requires a config.ini file (see source for explaination)
 * Source       : http://leehblue.com/sync-local-and-remote-databases/
 */

$mode = $argv[1];

if(isset($argv[2])) {
  $config = $argv[2];
  if(file_exists($config)) {
    $ini = parse_ini_file($config, true);
    $sshServer = $ini['remote']['ssh'];
    $rDbUser = $ini['remote']['username'];
    $rDbPass = $ini['remote']['password'];
    $rDbName = $ini['remote']['database'];
    $lDbUser = $ini['local']['username'];
    $lDbPass = $ini['local']['password'];
    $lDbName = $ini['local']['database'];
  }
}

if($mode == 'get') {
  $source ="mongodump -h $sshServer --db $rDbName --out ~/temp/";
  $target = "mongo $lDbName --eval 'db.dropDatabase();' && " .
  "mongorestore --host=localhost --db $lDbName ~/temp/$rDbName/ && " .
  "rm -rf ~/temp/$rDbName/";
  $cmd = "$source \n$target";
  echo "Replacing $lDbName on localhost with $rDbName from $sshServer\n\n";
  echo `$cmd`;
}
elseif($mode == 'put') {
  $source = "mongodump --db $lDbName --out ~/temp/\n" .
  "cd ~/temp && tar -zcf - $lDbName/ | ssh $sshServer 'tar -zxf'\n" .
  "rm ~/temp/$lDbName/";
  $target = "ssh $sshServer 'mongorestore --host=localhost --db $rDbName $lDbName/ && rm -rf $lDbName/'";
  $cmd = "$source \n$target";
  echo "Replacing $rDbName on $sshServer with $lDbName on localhost\n\n";
  echo `$cmd`;
}
echo "\n\nTransfer complete.\n\n";