#!/usr/bin/php
<?php

/**
 * Description  : Sync Mysql DB from remote to local host.
 * Usage        : db sync-mysql [get|put] [path/to/config.ini]
 * Dependencies : php, mysql-client
 * Example      : db sync-mysql get config.ini
 * Notes        : requires a config.ini file (see source for explaination)
 * Source       : http://leehblue.com/sync-local-and-remote-databases/
 */

$mode = $argv[1];

if(isset($argv[2])) {
  $config = $argv[2];
  if(file_exists($config)) {
    $ini = parse_ini_file($config, true);
    $sshServer = $ini['remote']['ssh'];
    $rDbUser = $ini['remote']['username'];
    $rDbPass = $ini['remote']['password'];
    $rDbName = $ini['remote']['database'];
    $lDbUser = $ini['local']['username'];
    $lDbPass = $ini['local']['password'];
    $lDbName = $ini['local']['database'];
  }
}

if($mode == 'get') {
  $source = "ssh $sshServer" . ' "' . "mysqldump -u $rDbUser --password=$rDbPass $rDbName | gzip" . '" ';
  $target = "gunzip | mysql -u $lDbUser --password=$lDbPass --host=localhost -C $lDbName";
  $cmd = " $source | $target";
  echo "Replacing $lDbName on localhost with $rDbName from $sshServer\n\n";
  echo `$cmd`;
}
elseif($mode == 'put') {
  $source = "mysqldump -u $lDbUser --password=$lDbPass --host=localhost -C $lDbName | gzip";
  $target = "ssh $sshServer" . ' "' . "gunzip | mysql -u $rDbUser --password=$rDbPass $rDbName" . '"';
  $cmd = $source . ' | ' . $target;
  echo "Replacing $rDbName on $sshServer with $lDbName on localhost\n\n";
  echo `$cmd`;
}
echo "\n\nTransfer complete.\n\n";