completions:
  repo: https://github.com/zsh-users/zsh-completions
  path: lib
oh-my-zsh:
  repo: https://github.com/robbyrussell/oh-my-zsh
  path: lib
solarized:
  repo: https://github.com/sigurdga/gnome-terminal-colors-solarized
  path: lib
syntax-highlighting:
  repo: https://github.com/zsh-users/zsh-syntax-highlighting
  path: lib
zaw:
  repo: https://github.com/zsh-users/zaw
  path: lib