#!/bin/zsh

# Install, if doesn't yet exists.
[[ -z `command -v "zsh"` ]] && sudo apt-get install -y zsh
chsh -s /bin/zsh

sudo apt-get install -y gconf2
cd $HOME/.zsh/lib/zsh-solarized
./set_dark.sh && zsh

# Link configuration to $HOME directory.
ln -s $HOME/.zsh/init/.zlogout $HOME/
ln -s $HOME/.zsh/init/.zshenv $HOME/
ln -s $HOME/.zsh/init/.zshrc $HOME/
ln -s $HOME/.zsh/init/.liquidpromptrc $HOME/

cd $HOME
rm .bash*
rm .profile

compaudit | xargs chmod g-w
# compaudit | xargs chmod 664