#!/usr/bin/env bash

# Description  : Silently remove all stopped containers.
# Usage        : docker rm-all
# Dependencies :
# Example      :
# Notes        :
# Source       : http://www.centurylinklabs.com/15-quick-docker-tips/

docker kill $(docker ps -a -q) 2>&1
docker rm $(docker ps -a -q) 2>&1