#!/usr/bin/env bash

# Description  : Silently remove all images.
# Usage        : docker rmi-all
# Dependencies :
# Example      :
# Notes        :
# Source       :

docker rmi $(docker ps -a -q) 2>&1