#!/usr/bin/env bash

# Description  : Prints the IP address of the last used docker container.
# Usage        : docker last-ip
# Dependencies :
# Example      :
# Notes        :
# Source       : http://www.centurylinklabs.com/15-quick-docker-tips/

docker inspect `docker-last` | grep IPAddress | cut -d '"' -f 4