#!/bin/bash

# Description  : Better docker attach using nsenter.
# Usage        : docker attach <container-name>
# Dependencies : nsenter, docker
# Example      : docker attach nginx
# Notes        : Can be either container name, ID or whatever.
# Source       : http://www.sebastien-han.fr/blog/2014/01/27/access-a-container-without-ssh
# Source       : http://www.colliernotes.com/2014/03/how-to-enter-docker-container-without.html

CONTAINER=$1
PID=`docker inspect --format '{{ .State.Pid }}' $CONTAINER`
sudo nsenter -m -u -n -i -p -t $PID /bin/bash