#!/usr/bin/env bash

# Description  : List branches by their update date and print information of each.
# Usage        : git latest-update
# Dependencies :
# Example      :
# Notes        :
# Source       : http://stackoverflow.com/a/18767922/865268

git branch -vv --color=always |
while read; do
  echo -e $(git log -1 --format=%ci $(echo "_$REPLY" | awk '{print $2}' | perl -pe 's/\e\[?.*?[\@-~]//g') 2> /dev/null || git log -1 --format=%ci)" $REPLY"
done | sort -r | cut -d ' ' -f -1,4-