#!/usr/bin/env bash

# Description  : Download a YouTube video and extract the music file from it.
# Usage        : misc youtube2mp3 [URL ...]
# Dependencies : youtube-dl ffmpeg lame
# Example      :
# Notes        :
# Source       :

set -x

function exit_script() {
  echo "$1"
  exit 1
}
function print_usage() {
  echo "Usage: misc youtube2mp3 [URL ...]"
  exit 0
}

if [[ $# == 0 ]]; then
  print_usage
fi

# Convertion Magic - Commense.
# ------------------------------------------------------------------------------------------------------------
cd $HOME/Downloads
REGEX='v=(.*)'
while (( $# > 0 )); do
  if [[ ! $1 =~ $REGEX ]]; then
    echo "'$1' is not a valid url" 1>&2
    shift
    continue
  fi

  VIDEO_FILENAME="$(youtube-dl --get-filename $1)"
  VIDEO_TITLE="$(youtube-dl --get-title $1)"

  youtube-dl $1
  avconv -i $VIDEO_FILENAME "$VIDEO_TITLE".wav
  lame "$VIDEO_TITLE".wav "$VIDEO_TITLE".mp3
  rm $VIDEO_FILENAME "$VIDEO_TITLE".wav

  shift
done