#!/usr/bin/env bash

# Description  : Create shell sub commands by hierarchy.
# Usage        : <command> <sub-command>
# Dependencies :
# Example      :
# Notes        : Generic script.
# Source       : http://stackoverflow.com/q/23683860/865268

set -e

command=`basename $0`
subcommand="$1"
case "$subcommand" in
"" | "-h" | "--help" )
  echo "$command: copy strings to clipboard" >&2
  ;;
* )
  subcommand_path="$(command -v "$command-$subcommand" || true)"
  if [[ -x "$subcommand_path" ]]; then
    shift
    exec "$subcommand_path" "${@}"
    return $?
  else
    echo "$command: no such command \`$subcommand'" >&2
    exit 1
  fi
  ;;
esac