#!/usr/bin/env bash

# Description  : Download a YouTube video and extract the music file from it.
# Usage        : misc youtube2mp3 <url>
# Dependencies : youtube-dl ffmpeg lame
# Example      :
# Notes        :
# Source       :

cd $HOME/Downloads
ADDRESS=$1
REGEX='v=(.*)'

if [[ $ADDRESS =~ $REGEX ]]; then
	video_filename="$(youtube-dl --get-filename $ADDRESS)"
	video_title="$(youtube-dl --get-title $ADDRESS)"
	youtube-dl $ADDRESS
	avconv -i $video_filename "$video_title".wav
	lame "$video_title".wav "$video_title".mp3
	rm $video_filename "$video_title".wav
else
	echo "Sorry but the system encountered a problem."
fi