#!/usr/bin/env bash

# Description  : Create shell sub commands by hierarchy on top of an existing command.
# Usage        : <command> <sub-command>
# Dependencies :
# Example      :
# Notes        : Generic script. Fallback to the original command, if there is one.
# Source       : http://stackoverflow.com/q/23683860/865268

set -e

command=`basename $0`
subcommand="$1"
case "$subcommand" in
"" | "-h" | "--help" )
  command $command "${@}"
  ;;
* )
  subcommand_path="$(command -v "$command-$subcommand" || true)"
  if [[ -x "$subcommand_path" ]]; then
    shift
    exec "$subcommand_path" "${@}"
    return $?
  else
    command $command "${@}"
    return 1
  fi
  ;;
esac