#!/usr/bin/env bash

# Description  : List the most commonly used commands and their statistics.
# Usage        : show common-commands
# Dependencies :
# Example      :
# Notes        :
# Source       : http://linux.byexamples.com/archives/332/what-is-your-10-common-linux-commands/

export HISTFILE=~/.zsh_history
fc -R

fc -l -10 |            # List history from .zsh_history
awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | # Create statistics usage
grep -v "./" |         # Print all results buy ones containing "./"
column -c3 -s " " -t | # Divide the information to columns
sort -nr |             # Sort the list by numeric, reversed
nl |                   # Add line numbers
head -n 10             # Show only top 10 results