#!/bin/zsh

# Navigation
alias ..="cd .."
alias ...="cd ../.."

# Listings
alias lsa='ls -laF --color=always'
alias lsd='ls -l | grep "^d"' # List only directories

# Information
alias empt="rm -rfv ~/.Trash" # Empty the Trash
alias fn='find . -name'

# Git
alias g="git"

# Super user
alias _='sudo'

# Midnight Commander
alias mc='. ~/.mc/bin/mc-wrapper' # Exit mc in the last directory

# Emacs
alias emacs="emacs-snapshot-gtk"