#!/bin/zsh

# Cdargs magic
function cv() {
  cdargs $(cat "$HOME/.cdargs" | awk '{print $1}' | fzf) &&
  cd "`cat "$HOME/.cdargsresult"`" &&
  clear
}
zle -N hd
bindkey '^[q' hd

# Show bundles to install
function install() {
  sudo apt-get install \
  "$(dpkg -l |
  awk '{print $2}' |
  fzf)"
}

# Show bundles to remove
function remove() {
  sudo apt-get --purge remove \
  "$(dpkg -l |
  awk '{print $2}' |
  fzf)"
  }

# present all projects in tmuxinator
function mux () {
  tmuxinator start \
  "$(find $HOME/.tmuxinator/ -name \*.yml |
  awk -F/ '{print $NF}' |
  sed s:.yml::g |
  fzf)" &&
  clear
}

# present all projects in tmuxinator
function clp () {
  cat ~/.cache/clipbored/clips | fzf | clip
}

# Adding description and removing it afterwards! format: "keyword" "description"
function tst () {
  git $(cat ~/.test |
  fzf |
  awk '{print $1}')
}

mkcd () {
  if [ ! -d $1 ]; then
      mkdir -p $1;
      cd $1;
  else
      echo "$1 directory exists";
  fi
}