#!/bin/zsh

# find and download all files with certain extension from a website
#	wget http://some.website.com > site
	# find unique instances of items in a file named "list"
#	grep -o '[^[:space:]]*.tar.bz2' site | sort -u > files
#	#get the files
#	wget -i files