#!/usr/bin/env bash

# Description  : Create shell sub commands by hierarchy on top of an existing command.
# Usage        : <command> <sub-command>
# Dependencies :
# Example      :
# Notes        : Generic script. Fallback to the original command, if there is one.
# Source       : http://stackoverflow.com/q/23683860/865268

# TODO: Add completions

set -e

COMMAND=`basename $0`
SUBCOMMAND="$1"
COMMAND_DIR="$HOME/.zsh/scripts/$COMMAND"

case "$SUBCOMMAND" in
  "" | "-h" | "--help" )
    cat "$COMMAND_DIR/help.txt" 2>/dev/null ||
    command $COMMAND "${@}"
    ;;
  * )
    SUBCOMMAND_path="$(command -v "$COMMAND-$SUBCOMMAND" || true)"
    if [[ -x "$SUBCOMMAND_path" ]]; then
      shift
      exec "$SUBCOMMAND_path" "${@}"
    else
      command $COMMAND "${@}"
    fi
    ;;
esac