#!/usr/bin/env bash

# Description  : Create shell sub commands by hierarchy on top of an existing command.
# Usage        : <command> <sub-command>
# Dependencies :
# Example      :
# Notes        : Generic script. Fallback to the original command, if there is one.
# Source       : http://stackoverflow.com/q/23683860/865268
# Source       : http://stackoverflow.com/a/4774063/865268

# TODO: Add completions

set -e

COMMAND=`basename $0`
SUBCOMMAND=$1

SUBCOMMAND_PATH="$(command -v "$COMMAND-$SUBCOMMAND" || true)"
COMMAND_DEFAULT="$(command -v "$COMMAND-default" || true)"

if [[ -x "$SUBCOMMAND_PATH" ]]; then
  shift
  exec "$SUBCOMMAND_PATH" "${@}"
elif [[ -x "$COMMAND_DEFAULT" ]]; then
  exec "$COMMAND_DEFAULT" "${@}" 2>/dev/null
else
  [[ `command -v $COMMAND` == $0 ]] && exit 1
  eval $COMMAND "${@}"
fi