#!/usr/bin/env bash

# Description  : Copy SSH Public Key to clipboard
# Usage        : clp ssh
# Dependencies : clp(), xclip
# Example      :
# Notes        :
# Source       :

cat "~/.ssh/id_rsa.pub" | clip