#!/bin/bash

# Description  : Download & Extract a compressed file from a url.
# Usage        : extract-upstream <URL> <Dest>
# Dependencies : bsdtar, tar, wget, p7zip
# Example      : extract upstream "http://wordpress.org/latest.zip" ~/Downloads
# Notes        :
# Source       : http://stackoverflow.com/a/23108309; oh-my-zsh extract plugin

if [[ $# == 0 ]]; then
  echo "Usage: extract-upstream [URL] [Destination]"
fi

EXTRACT_DEST=$2
if [[ -z $2 ]]; then
  EXTRACT_DEST=`pwd`
fi

file_name="$( basename "$1" )"
case "$1" in
  (*.tar.gz|*.tgz) wget -qO- "$1" | tar -xvzf- -C "$EXTRACT_DEST" ;;
  (*.tar.bz2|*.tbz|*.tbz2) wget -qO- "$1" | tar -xvjf- -C "$EXTRACT_DEST" ;;
  (*.zip|*.rar|*.tar) wget -qO- "$1" | bsdtar -xvf- -C "$EXTRACT_DEST" ;;
  (*.gz) wget -qO- "$1" | 7z -si -tgzip x -o$EXTRACT_DEST ;;
  (*.bz2) wget -qO- "$1" | 7z -si -tbzip2 x -o$EXTRACT_DEST ;;
  (*.7z) wget -qO- "$1" | 7za -si x -o"$EXTRACT_DEST" ;;
  (*) echo "extract: '$1' cannot be extracted" 1>&2 ;;
esac