#!/usr/bin/env bash

# Description  : Download & Extract a compressed file from a url.
# Usage        : extract-upstream <URL> <Dest>
# Dependencies : bsdtar, tar, wget, p7zip
# Example      : extract upstream "http://wordpress.org/latest.zip" ~/Downloads
# Notes        :
# Source       : http://stackoverflow.com/a/23108309; oh-my-zsh extract plugin

if [[ $# == 0 ]]; then
  echo "Usage: extract-upstream <URL> <Destination>"
fi

EXTRACT_DIR=$2
if [[ -z $2 ]]; then
  EXTRACT_DIR=`pwd`
fi
if [[ ! -d $2 ]]; then
  mkdir -p $2
fi

file_name="$( basename "$1" )"
case "$1" in
  (*.tar.gz|*.tgz) wget -qO- "$1" | tar -xvzf- -C "$EXTRACT_DIR" ;;
  (*.tar.bz2|*.tbz|*.tbz2) wget -qO- "$1" | tar -xvjf- -C "$EXTRACT_DIR" ;;
  (*.zip|*.rar|*.tar) wget -qO- "$1" | bsdtar -xvf- -C "$EXTRACT_DIR" ;;
  (*.gz) wget -qO- "$1" | 7za -si -tgzip x -o$EXTRACT_DIR ;;
  (*.bz2) wget -qO- "$1" | 7za -si -tbzip2 x -o$EXTRACT_DIR ;;
  (*.7z) wget -qO- "$1" | 7za -si x -o"$EXTRACT_DIR" ;;
  (*) echo "extract: '$1' cannot be extracted" 1>&2 ;;
esac