#!/bin/bash

# Description  : Use multiple ssh config files to define hosts.
# Usage        : ssh-concat <host-name>
# Dependencies :
# Example      : ssh-concat nginx.docker
# Notes        :
# Source       : http://www.linuxsysadmintutorials.com/multiple-ssh-client-configuration-files/
# Source       : https://stackoverflow.com/questions/12037634/bash-cat-multiple-files

ssh-concat() {
  TMPDIR=~/tmp
  case "$(uname -s)" in
    Linux)
      tmp_fifo=$(mktemp -u --suffix=._ssh_fifo)
      ;;
    Darwin)
      tmp_fifo=$(mktemp -u -t ._ssh_fifo)
      ;;
    *)
      echo 'unsupported OS'
      exit
      ;;
  esac

  # cleanup first
  rm ~/tmp/._ssh_fifo* 2>/dev/null

  mkfifo "$tmp_fifo"
  cat ~/.ssh/config ~/.ssh/config.* >"$tmp_fifo" 2>/dev/null &
  /usr/bin/ssh -F "$tmp_fifo" "$@"
  rm "$tmp_fifo"
}

ssh-concat $*