#!/bin/bash

# Description  : Proxy an ssh connection to a tunnel via <instance-name>.tunnel
# Usage        : ssh <instance-name>.tunnel <port>
# Dependencies : nc, ssh, autossh, corkscrew
# Example      : ssh wix-people-aws.tunnel
# Notes        : Called from ~/.ssh/config file
# Source       : http://www.noah.org/wiki/SSH_tunnel
# Source       : http://unix.stackexchange.com/a/46271
# Source       : http://stackoverflow.com/a/4396415/865268
# Source       : http://erik.torgesta.com/2013/12/creating-a-persistent-ssh-tunnel-in-ubuntu/

# Set up autossh (or just ssh tunnel) in the background
#   + Just add -fqTN flags to ssh
# List all avaialable ssh tunnels
#   + ps aux | grep ssh
#   + netstat -n --protocol inet | grep ':22'
#   + sudo lsof -i -n | egrep '\<ssh\>'