#!/bin/bash

# Description  : Ssh and execute a command using sudo.
# Usage        : ssh <server> <command>
# Dependencies :
# Example      : ssh er-web01 "ls -la"
# Notes        :
# Source       : http://mattconnolly.wordpress.com/2011/11/02/sudo-with-askpass/

ssh '$1' SUDO_ASKPASS=/usr/lib/ssh-askpass sudo -A '$2'