#!/bin/bash

# Description  :
# Usage        :
# Dependencies :
# Example      :
# Notes        :
# Source       : http://www.revsys.com/writings/quicktips/ssh-tunnel.html

ssh '$1' SUDO_ASKPASS=/usr/lib/ssh/ssh-askpass sudo -A '$2'