#!/usr/bin/env bash

# Description  : Use multiple ssh config files to define hosts.
# Usage        : ssh-concat <host-name>
# Dependencies :
# Example      : ssh-concat nginx.docker
# Notes        :
# Source       : http://www.linuxsysadmintutorials.com/multiple-ssh-client-configuration-files/
# Source       : https://stackoverflow.com/questions/12037634/bash-cat-multiple-files

case "$(uname -s)" in
  Linux)
    tmp_fifo=$(mktemp -u --suffix=._ssh_fifo)
    ;;
  Darwin)
    tmp_fifo=$(mktemp -u -t ._ssh_fifo)
    ;;
  *)
    echo 'unsupported OS'
    exit
    ;;
esac

# cleanup first
rm ~/tmp/._ssh_fifo* 2>/dev/null

mkfifo "$tmp_fifo"
for file in /etc/ssh/ssh_config ~/.ssh/config ~/.ssh/config.d/*; do
  cat $file <(echo)
done > "$tmp_fifo" &

/usr/bin/ssh -F "$tmp_fifo" "$@"
rm "$tmp_fifo"