#!/usr/bin/expect

# Description  : SSH to a server with tty and execute a command.
# Usage        : ssh <server> <command>
# Dependencies : expect, ssh
# Example      : ssh er-web01 "cd /var/www; clear"
# Notes        :
# Source       :

set timeout 2

set ssh [lindex $argv 0]
set cwd [lindex $argv 1]
set pass [lindex $argv 2]

spawn ~/.zsh/scripts/ssh/ssh "$ssh"

if { $pass != "" } {
	expect assword
	send "$pass\n"
	}

expect "~]$"
send "cd $cwd && clear\n"
interact