#!/bin/bash

# Description  : Recursively change permissions of all the directories in a directory to "fresh" start.
# Usage        : chmod init-folders
# Dependencies :
# Example      :
# Notes        :
# Source       : http://superuser.com/a/91938

find . -type d -print0 | xargs -0 chmod 0755