#!/usr/bin/env bash

# Description  :
# Usage        :
# Dependencies :
# Example      :
# Notes        :
# Source       :

set -e

command=`basename $0`
subcommand="$1"
case "$subcommand" in
"" | "-h" | "--help" )
  command $command "${@}"
  ;;
* )
  subcommand_path="$(command -v "$command-$subcommand" || true)"
  if [[ -x "$subcommand_path" ]]; then
    shift
    exec "$subcommand_path" "${@}"
    return $?
  else
    command $command "${@}"
    return 1
  fi
  ;;
esac