#!/usr/bin/env bash

# Description  : Recursively change permissions of all the files in a directory to "fresh" start.
# Usage        : chmod init-files
# Dependencies :
# Example      :
# Notes        : See other examples in the attached Source URL
# Source       : http://superuser.com/a/91938

find . -type f -print0 | xargs -0 chmod 0644